name: Build and Deploy the website
on:
  push:
    branches: [ master ]

jobs:
  buildDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Build
        run: npm ci && npm run production --if-present

      - name: List output files
        run: ls

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://goethe.metanet.ch/
          ftp-username: github-pizza-selector
          ftp-password: ${{ secrets.FTP_PASSWORD }}

